name: flutter_nemid
description: A Flutter plugin for NemID integration on Android and iOS
version: 0.0.1
homepage: https://github.com/meewworld/flutter_nemid

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.meew.flutter_nemid
        pluginClass: FlutterNemidPlugin
      ios:
        pluginClass: FlutterNemidPlugin
